
version: "3.6"
services:
  laernlp:
     build:
        context: "https://$gitusername:$gitpassword@github.com/laergithubtest/LaerNLP.git#v2018.12.21.0"
        args:
           - maven
     volumes:
        - type: volume
          source: laernlp-maven-cache
          target: /root/.m2

  mongo:
     container_name: mongo
     image: laerinternal.com/mongo:0.1
     volumes:
        - mongo-data:/data/db

  solr:
     container_name: solr
     image: solr 
     volumes:
         - type: volume
           source: solr-data
           target: /opt/solr/server/solr

  query-parser:
     container_name: query-parser
     depends_on:
        - laernlp
        - mongo
     build:
        context: "https://$gitusername:$gitpassword@github.com/laergithubtest/query-parser.git"
        args:
            - mongo_db_key
            - gitusername
            - gitpassword
     volumes:
        - type: volume
          source: out-enron
          target: /out-enron
          read_only: true

        - type: volume
          source: knowledge
          target: /knowledge
          read_only: true
     ports:
         - "1232:1200"
     environment:
                
        - LAERNLP_URI=http://laernlp:9000
        - MONGODB_IP=mongo
        - MONGODB_PORT=27017
        - SOLR_IP=solr
        - SOLR_PORT=8983
        - CORENLP_PARSER=http://query-parser
        - CORENLP_PARSER_PORT=1200
        - QUERY_PARSER=http://query-parser
        - QUERY_PARSER_PORT=1200
        - SEMANTIC_PARSER=http://semantic-parser
        - SEMANTIC_PARSER_PORT=1200
        - QUERY_EXECUTOR=http://query-executor
        - QUERY_EXECUTOR_PORT=1200

        - EMBEDDING_PATH=/knowledge
        - WAIT_HOSTS=laernlp:9000,mongo:27017
        - WAIT_HOSTS_TIMEOUT=300
     command: sh -c "/wait && cd /root/query-parser && python server.py --case_path /out-enron"

  semantic-parser:
     container_name: semantic-parser
     build:
        context: "https://$gitusername:$gitpassword@github.com/laergithubtest/semantic-parser.git"
        args:
            - maven
     volumes:
        - type: volume
          source: semantic-parser-maven-cache
          target: /root/.m2
     ports:
         - "1234:1200"
     environment:
                
        - LAERNLP_URI=http://laernlp:9000
        - MONGODB_IP=mongo
        - MONGODB_PORT=27017
        - SOLR_IP=solr
        - SOLR_PORT=8983
        - CORENLP_PARSER=http://query-parser
        - CORENLP_PARSER_PORT=1200
        - QUERY_PARSER=http://query-parser
        - QUERY_PARSER_PORT=1200
        - SEMANTIC_PARSER=http://semantic-parser
        - SEMANTIC_PARSER_PORT=1200
        - QUERY_EXECUTOR=http://query-executor
        - QUERY_EXECUTOR_PORT=1200

        - WAIT_HOSTS=query-parser:1200
        - WAIT_HOSTS_TIMEOUT=300
     command: sh -c "/wait && python3 run.py server"

  query-executor:
     container_name: query-executor
     depends_on:
        - mongo
        - solr
        - query-parser
        - semantic-parser
     volumes:
        - type: volume
          source: query-executor-maven-cache
          target: /root/.m2
     build:
        context: "https://$gitusername:$gitpassword@github.com/laergithubtest/query-executor.git"
        args:
            - maven
     ports:
         - "1235:1200"
     environment:
                
        - LAERNLP_URI=http://laernlp:9000
        - MONGODB_IP=mongo
        - MONGODB_PORT=27017
        - SOLR_IP=solr
        - SOLR_PORT=8983
        - CORENLP_PARSER=http://query-parser
        - CORENLP_PARSER_PORT=1200
        - QUERY_PARSER=http://query-parser
        - QUERY_PARSER_PORT=1200
        - SEMANTIC_PARSER=http://semantic-parser
        - SEMANTIC_PARSER_PORT=1200
        - QUERY_EXECUTOR=http://query-executor
        - QUERY_EXECUTOR_PORT=1200

        - WAIT_HOSTS=mongo:27017,solr:8983,query-parser:1200,semantic-parser:1200
        - WAIT_HOSTS_TIMEOUT=300
     command: sh -c "/wait && cd /root/query-executor && ./run.sh"

volumes:

  out-enron:
    name: out-enron
#    external: true

  mongo-data:
    name: mongo-data
#    external: true

  knowledge:
    name: knowledge
#    external: true

  solr-data:
    name: solr-data
#    external: true

  laernlp-maven-cache:
    name: laernlp-maven-cache
#    external: true

  semantic-parser-maven-cache:
    name: semantic-parser-maven-cache

  query-executor-maven-cache:
    name: query-executor-maven-cache
